---
version: "2.0"

services:
  web:
    # Replace with the image you build and push to a container registry
    # e.g., yourusername/cryptotrend-ai:latest
    image: ghcr.io/rashelshah/cryptotrend-ai:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 10000

deployment:
  web:
    dcloud:
      profile: web
      count: 1